version: "2.0"

services:
    ammunation-backend:
        build: .
        environment:
            - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
        expose:
            - "80" # REST Api, Monitoring Api & Swagger
            - "5005" # Application debug port
        ports:
            - "8989:8080"
            - "5005:5005"
        depends_on:
            - database
        links:
            - database
    database:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: ammunation
            MYSQL_DATABASE: app
        expose:
            - "3306"
        ports:
            - "8080:3306"
    frontend:
        image: nginx:latest
        volumes:
              - ./web:/usr/share/nginx/html
        expose:
            - "80" # Web Client
        ports:
            - "7080:80"
